/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package env_easy_setup;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import env_easy_setup.Model.Docker;

@Component
public class Library {
	@Autowired
	private AppsConfiguration appsConfiguration;
	@Autowired
	private EveryStepMethod everyStepMethod;
	
    public void printFields() {
    	everyStepMethod.initSysInfo();
//    	System.out.println(appsConfiguration.getDocker().getVersion());
//
//    	System.out.println(appsConfiguration.getElasticsearch().getVersion());
//
//    	System.out.println(appsConfiguration.getFilebeat().getVersion());
//    	
//    	System.out.println(appsConfiguration.getHarbor().getVersion());

    	
    }
}
