/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package env_easy_setup;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class Library {
	@Autowired
	private AppsConfiguration appsConfiguration;
	@Autowired
	private EveryStepMethod everyStepMethod;
	
    public void printFields() {
    	Map<String,String> params=new HashMap<String,String>();
    	
    	params.put("HARBOR_CA_NAME", "harbor_ca_name");
    	
    	params.put("HARBOR_SERVER", "harbor_server");

    	
    	
    	
    	everyStepMethod.tempToKeyShell(params);
//    	everyStepMethod.initSysInfo();
    	
    	
    }
}
