sys-info:
  path: /
  os: linux
  memory: 
  storage: 
apps:
  sysinfo:
    version: '1.0.0'
    select: true
    rpm-path:
  docker:
    version: '20.10.21-3'
    select: true
    rpm-path:
  harbor: 
    version: '2.6.1'
    select: true
    rpm-path:
  rke2:
    version: '1.24.8'
    select: true
    rpm-path:
  rancher:
    version: '2.6.9'
    select: true
    rpm-path:
  kafka:
    version: '2.13-3.31'
    select: true
    rpm-path:
  elasticsearch:
    version: '7.17'
    select: true
    rpm-path:
  kibana:
    version: '7.17'
    select: true
    rpm-path:
  filebeat:
    version: '7.17'
    select: true
    rpm-path:
tls-config:
    encrypt-conn: true
    key-model:
      - name: elasticsearch
        type: PKCS12
        ca-name: elasticsearch-ca
        server-name: elasticsearch-server
        client-name: elasticsearch-client
        store-name: elasticsearch
        validity-day: 3650
        subject: ""
      - name: kibana
        type: cert
        ca-name: kibana-ca
        server-name: kibana-server
        client-name: kibana-client
        store-name: kibana
        validity-day: 3650
        subject: ""
      - name: harbor
        type: cert
        ca-name: harbor-ca
        server-name: harbor-server
        client-name: harbor-client
        store-name: harbor
        validity-day: 3650
        subject: ""
      - name: kafka
        type: JKS
        ca-name: kafka-ca
        server-name: kafka-server
        client-name: kafka-client
        store-name: kafka
        validity-day: 3650
        subject: ""
      - name: filebeat
        type: cert
        ca-name: filebeat-ca
        server-name: filebeat-server
        client-name: filebeat-client
        store-name: filebeat
        validity-day: 3650
        subject: ""
  
   
    
  