sys-info:
  path: /
  os: linux
  memory: 
  storage: 
apps:
  sysinfo:
    version: '1.0.0'
    select: true
    rpm-path:
  docker:
    version: '20.10.21-3'
    select: true
    rpm-path:
  harbor: 
    version: '2.6.1'
    select: true
    rpm-path:
  rke2:
    version: '1.24.8'
    select: true
    rpm-path:
  rancher:
    version: '2.6.9'
    select: true
    rpm-path:
  kafka:
    version: '2.13-3.31'
    select: true
    rpm-path:
  elasticsearch:
    version: '7.17'
    select: true
    rpm-path:
  kibana:
    version: '7.17'
    select: true
    rpm-path:
  filebeat:
    version: '7.17'
    select: true
    rpm-path:
tls-config:
    encrypt-conn: true
    key-model:
      - name: elasticsearch
        type: PKCS12
        subject:
      - name: kibana
        type: cert
        subject:
      - name: harbor
        type: cert
        subject:
      - name: kafka
        type: JKS
        subject:
      - name: filebeat
        type: cert
        subject:
  
   
    
  